# Generated by Django 2.0.6 on 2018-07-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',null=True)),
                ('name', models.CharField(max_length=100,null=True)),
                ('email', models.EmailField(max_length=254,null=True)),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True,null=True)),
                ('updated', models.DateTimeField(auto_now=True,null=True)),
                ('active', models.BooleanField(default=True,null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post',null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
